categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"

  - title: ":rocket: Features"
    label: "enhancement"

  - title: ":fire: Removals and Deprecations"
    label: "removal"

  - title: ":bug: Fixes"
    label: "bug"

  - title: ":racehorse: Performance"
    label: "performance"

  - title: ":rotating_light: Testing"
    label: "testing"

  - title: ":construction_worker: Continuous Integration"
    label: "ci"

  - title: ":books: Documentation"
    label: "documentation"

  - title: ":hammer: Refactoring"
    label: "refactoring"

  - title: ":lipstick: Style"
    label: "style"

  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"

category-template: "### $TITLE"
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

# Custom text at start of release
header: >

  Insert header here...

template: |

  ## What's Changed

  $CHANGES

footer: |

  **Full changelog:** [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/robbievanleeuwen/section-properties/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
