version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    # https://docs.readthedocs.com/platform/stable/build-customization.html#install-dependencies-with-uv
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - uv python install 3.13
    create_environment:
      - uv venv -p 3.13
    install:
      - uv sync -p 3.13 --frozen --extra rhino --extra dxf --no-group dev --no-group lint --no-group test
    build:
      html:
        - uv run -p 3.13 --no-sync sphinx-build -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
