version: 2

build:
  os: ubuntu-22.04
  tools:
    python: latest
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv python install 3.12
    - uv sync -p 3.12 --frozen --extra rhino --extra dxf --no-group test --no-group lint
    - uv run -p 3.12 --no-sync -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
